---
- name: Restart microceph daemon
  ansible.builtin.command:
    cmd: snap restart microceph.daemon

- name: Reboot if needed
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Restart systemd daemon
  ansible.builtin.command:
    cmd: systemctl daemon-reload
