---
dependencies: []

galaxy_info:
  role_name: ansible_role_microceph
  namespace: pitabwire
  author: Peter Bwire
  description:
  issue_tracker_url: https://github.com/pitabwire/ansible-role-microcep/issues
  company: "Ant Investor, LTD"
  license: "MIT"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - ceph
    - storage
    - kubernetes
    - microk8s
    - microceph
