---

dependency:
  name: galaxy

driver:
  name: ${LSR_MOLECULE_DRIVER:-docker}

lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: "single-node-${MOLECULE_DISTRO:-ubuntu2204}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - storage_nodes
      - "${MOLECULE_DISTRO_FAMILY:-ubuntu}"

provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  inventory:
    links:
      hosts: inventory.yml

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
