- name: Make sure epel-release is installed
  ansible.builtin.dnf:
    name:
      - epel-release
    state: latest

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    allowerasing: true

- name: Add Ceph RPM repo
  ansible.builtin.template:
    src: ../templates/ceph-repo.j2
    dest: /etc/yum.repos.d/ceph.repo
    mode: '0644'

- name: Make sure snapd is installed
  ansible.builtin.dnf:
    name:
      - snapd
      - squashfs-tools
      - ceph-common
    state: latest

- name: Enable main snap communication socket
  ansible.builtin.command:
    cmd: systemctl enable --now snapd.socket

- name: Enable classic snap support symbolic link 
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link  
  notify: Reboot if needed

- name: Install microceph
  ansible.builtin.snap:
    name: microceph
    channel: "{{ microceph_version }}"
    state: present
  notify: Reboot if needed

- name: Enable rbd kernel module
  community.general.modprobe:
    name: rbd
    persistent: present
    state: present
  notify: Reboot if needed

- name: Allow snap to observe hardware interface
  ansible.builtin.command:
    cmd: snap connect microceph:hardware-observe
  changed_when: false

# Flush handlers after the package installation
- name: Flush handlers to reboot host
  ansible.builtin.meta: flush_handlers

